### ISSUE TITLE
plugins.py doesn't extract file attributes from .zip file

### ISSUE THREAD

**Issue by Slach** [integr8ly/grafana_plugins_init#1]
Steps to reproduce
```yaml
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  name: "My Dashboard"
  labels:
    app: grafana
spec:
  name: my_dashboard.json
  url: https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/grafana-dashboard/Altinity_ClickHouse_Operator_dashboard.json
  datasources:
    - inputName: "DS_PROMETHEUS"
      datasourceName: "prometheus"
  plugins:
    - name: "vertamedia-clickhouse-datasource"
      version: "2.0.2"
```

clickhouse deployment not ready to start with following error message
```
grafana t=2020-07-20T11:04:18+0000 lvl=eror msg="Failed to init plugin." logger=plugins error="fork/exec /var/lib/grafana/plugins/Vertamedia-clickhouse-grafana-8 ││ 601b8f/dist/vertamedia-clickhouse-plugin_linux_amd64: permission denied" plugin=vertamedia-clickhouse-datasource
```

when run 
```bash
ls -la /var/lib/grafana/plugins/Vertamedia-clickhouse-grafana-8601b8f/dist/*linux*
```

then we see execute attributes is not present
```
-rw-r--r--    1 root     root      14788192 Jul 20 11:04 /var/lib/grafana/plugins/Vertamedia-clickhouse-grafana-8601b8f/dist/vertamedia-clickhouse-plugin_linux_amd64
```

but when we try to 
```bash
cd /tmp
wget -O clickhouse-grafana.2.0.2.zip https://grafana.com/api/plugins/vertamedia-clickhouse-datasource/versions/2.0.2/download
unzip clickhouse-grafana.2.0.2.zip
ls -la Vertamedia-clickhouse-grafana-8601b8f/dist/*linux*
```
execute attibutes exists
```
-rwxr-xr-x 1 root root 14788192 Jul  20 03:22 vertamedia-clickhouse-plugin_linux_amd64
```

possible solution here
https://stackoverflow.com/a/39296577/1204665
